### ISSUE TITLE
Geometry not being shown correctly unless it's the first model loaded in BIMServer 1.4

### ISSUE THREAD

**Issue by tldddd** [opensourceBIM/BIMsurfer-before2019#221]
The same IFC model displays correctly in Navisworks and others viewers.

- In BIMServer 1.4, if it is the first model opened in BIMViews, the geometry all displays correctly.
- In BIMServer 1.4, if it is the second or third model opened, the geometry does not display correctly.
- In BIMServer 1.5, the model always does not display correctly, however the errors are different to the errors in BIMServer 1.4
- In the latest build of BIMSurfer using XeoGL, it does not display correctly.

I've checked and the JSON is received from BIMServer is the same but is being displayed different so I'm very sure the bug is in BIMSurfer, not BIMServer or IfcOpenShell. Especially because as the first picture below shows, it sometimes DOES render it correctly if it's the first model opened in BIMServer 1.4 (but never does in BIMServer 1.5).

The error is generally geometry out of place by a certain offset in one axis, and often the arrays actually have MORE elements than are specified in the IFC file.

_bimserver 1_4_0 plugin - When it's the first model opened - NO ERRORS:_
![bimserver 1_4_0 plugin - When it's the first model opened - NO ERRORS](https://user-images.githubusercontent.com/33082902/32106722-5d811494-bb24-11e7-9fc8-3fddaecf7d5f.PNG)

_bimserver 1_4_0 plugin - When it's not the first model opened ERROR:_
![bimserver 1_4_0 plugin - When it's not the first model opened.](https://user-images.githubusercontent.com/33082902/32106838-c0e496dc-bb24-11e7-809e-a4b233850a79.PNG)

_bimserver 1_5_88 plug in ERRORS:_
![bimserver 1_5_88 plug in ERRORS](https://user-images.githubusercontent.com/33082902/32106723-5d9e62c4-bb24-11e7-80be-0956539b5a02.PNG)

_latestbimsurfer ERRORS:_
![latestbimsurfer ERRORS](https://user-images.githubusercontent.com/33082902/32106724-5dc52170-bb24-11e7-9fb2-863f35b04ece.PNG)

If you have any ideas on how to fix this, or where in the code you believe the code could be going wrong so I could have a look, I'd be extremely grateful. Thanks very much!

**Comment by rubendel** [comment]
Are you loading multiple (different) models in the same view? In that case it might be related to a recently fixed bug in BIMsurfer. That has been fixed in BIMsurfer V1 and V2. You might want to patch your version of BIMsurfer, so see if that helps.

https://github.com/opensourceBIM/BIMsurfer/commit/c63c1214da86e7825892deb72c8570d12e345dba

**Comment by tldddd** [comment]
Thanks for the heads up about that fixed bug.

Unfortunately I don't think it's related to that bug because on BIMServer 1.5.88 (BIMSurfer V2) even when it's a single project with a single model the geometry displays incorrectly.

That bug may be related to the incorrect geometry in BIMServer 1.4 but it doesn't fix the BIMServer 1.5 problem.

Is there any other information I can give you or things you can think of that I could test to find the cause of this problem? Thanks again!

**Comment by rubendel** [comment]
Can you perhaps share the model?

**Comment by tldddd** [comment]
I would if I could, but unfortunately I can't publicly share anything beyond these screenshots.

**Comment by rubendel** [comment]
Oke. Can you maybe try the fix I mentioned anyways? The fix is not for 1.4 but for 1.5, and it's from last Friday.

**Comment by tldddd** [comment]
I will do. I'm a little confused about the branches for the repository, are both Branch **V1** (Scene.js) and Branch **Master** (Xeogl) compatible with BIMServer 1.5?

**Comment by rubendel** [comment]
I understand the confusion, but they both are. V1 is still being used in BIMvie.ws, at some point we'll move to V2. For new development V2 is recommended as it is developed with integration in mind.

**Comment by tldddd** [comment]
I've tried the fix using BIMSurfer V2 and it's not made a difference I'm afraid.

There must be something wrong with the geometry processing. The reason I am sure is that feeding the JSON into the BIMSurfer bundled with BIMServer 1.4 produces a correct model, but feeding the exact same JSON in the BIMSurfer bundled with BIMServer 1.5 and BIMSurfer V2 produces an error.

If I get an ID of the element that I know is going wrong, could you suggest where in the code I can set breakpoints so I can inspect how the geometry is being loaded?

**Comment by rubendel** [comment]
I don't think it's in the JSON. The JSON is only used for the semantic information in the model (to build the tree etc...). The actual geometry is loaded via a websocket in a binary format.

I can't really do anything with an ID without the model. All geometry is loaded in GeometryLoader.js (v1) or BimServerGeometryLoader.js (v2)

**Comment by tldddd** [comment]
Ah, I didn't realize the geometry was in a binary format. I'll have a look in those files.
